Check for git update failure In cases where git submodule update fails, the script enters an infinite loop calling itself.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7,6 +7,10 @@ npm install jasmine-node express wrench@1.3.6 jWorkflow mustache node-zip node-n
 if [ "$1" != "-scm" ]; then 
     git submodule update --init;
 fi
+if [ ! -e ./dependencies/webplatform/framework ]; then
+    echo "Fail: git submodule update (dependencies/webplatform/framework)"
+    exit 1
+fi
 cd ./dependencies/webplatform/framework;
 if [[ "$OS" == *Windows* ]]; then
     source configure;
